//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.21 at 12:50:00 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://grupo7.com/spring-boot-soap-ejemplo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.grupo7.spring_boot_soap_ejemplo;
